// ExamKit - Main Typst Template
// Auto-generated exam preparation notes

#import "theme.typ": *

// Document configuration
#let conf(
  title: none,
  author: "ExamKit",
  date: none,
  doc
) = {
  // Page setup
  set page(
    paper: "a4",
    margin: (x: 1in, y: 1in),
    header: [
      #set text(size: 9pt)
      #grid(
        columns: (1fr, 1fr),
        align: (left, right),
        [#title],
        [Exam Preparation Notes]
      )
      #line(length: 100%, stroke: 0.5pt)
    ],
    footer: [
      #line(length: 100%, stroke: 0.5pt)
      #set text(size: 9pt)
      #grid(
        columns: (1fr, 1fr),
        align: (left, right),
        [#date],
        [Page #counter(page).display("1 of 1", both: true)]
      )
    ]
  )

  // Typography
  set text(
    font: "New Computer Modern",
    size: 11pt,
    lang: "en"
  )

  set par(
    justify: true,
    leading: 0.65em,
    spacing: 1.2em
  )

  // Headings
  set heading(numbering: "1.1")
  show heading.where(level: 1): it => {
    pagebreak(weak: true)
    v(1em)
    text(size: 18pt, weight: "bold")[#it]
    v(0.5em)
  }
  show heading.where(level: 2): it => {
    v(0.8em)
    text(size: 14pt, weight: "bold")[#it]
    v(0.4em)
  }
  show heading.where(level: 3): it => {
    v(0.6em)
    text(size: 12pt, weight: "semibold")[#it]
    v(0.3em)
  }

  // Code blocks
  show raw.where(block: true): it => {
    block(
      fill: luma(245),
      inset: 10pt,
      radius: 4pt,
      width: 100%,
      it
    )
  }

  // Lists
  set enum(indent: 1em)
  set list(indent: 1em)

  // Links
  show link: it => {
    text(fill: blue)[#it]
  }

  // Math
  set math.equation(numbering: "(1)")

  // Title page
  if title != none {
    align(center)[
      #v(2cm)
      #text(size: 24pt, weight: "bold")[#title]
      #v(1cm)
      #text(size: 12pt)[Generated by ExamKit]
      #v(0.5cm)
      #text(size: 11pt)[#date]
      #v(2cm)
    ]
  }

  // Table of contents
  outline(
    title: "Contents",
    depth: 2,
    indent: auto
  )

  pagebreak()

  // Document body
  doc
}
